insert into person (nome) values ('ivson fff');
insert into person (nome) values ('ivson bbb');
insert into person (nome) values ('ivson ccc');
insert into person (nome) values ('ivson aaa');
insert into person (nome) values ('ivson eee');
insert into person (nome) values ('ivson ddd');
insert into person (nome) values ('algebra');
insert into person (nome) values ('teste');
insert into person (nome) values ('matematica');
insert into person (nome) values ('xis');
